services:
  SqlServer:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password@123456
    ports:
      - "1434:1433"
  Redis:
    image: redis
    ports:
    - "6379:6379"
  api:
    build:
      context: ./src/MataAtlantica.Api
    environment:
      - ConnectionStrings__Default=Server=SqlServer,1433; Database=MataAtlanticaDB; User Id=sa; Password=Password@123456; TrustServerCertificate=true;
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
    ports:
      - "8080:8080"
    depends_on:
      - SqlServer
      - Redis