@MataAtlantica.API_HostAddress = https://localhost:7188

###

GET {{MataAtlantica.API_HostAddress}}/api/fornecedores/string

###
GET {{MataAtlantica.API_HostAddress}}/api/fornecedores

###

@fornecedorId=3c2de4f3-7691-44f7-9fc6-0865271a1c5a
PUT {{MataAtlantica.API_HostAddress}}/api/fornecedores/{{fornecedorId}}
Content-Type: application/json
  {
      "nome": "Nivea(alterado)(alterado)",
      "descricao": "Grande vendedora de cosméticos(alterado)",
      "localizacao": {
        "rua": "asdasd(alterado)",
        "bairro": "Bairro das pedras(alterado)",
        "numero": "1231",
        "cidade": "Florianopolis",
        "uf": "SP",
        "cep": "400000000"
      },
      "cpfCnpj": "XXX.XXX.XXX/0001-sXdX",
      "telefone": "(17) 99999-9999"
    }

###

GET {{MataAtlantica.API_HostAddress}}/api/produtos

###

GET {{MataAtlantica.API_HostAddress}}/api/produtos

###

@id=0fe3eb77-32b8-4c20-945a-02db4f0c498e
PUT {{MataAtlantica.API_HostAddress}}/api/produtos/{{id}}
Content-Type: application/json
{
  "Nome": "asdasd"
}

###

GET {{MataAtlantica.API_HostAddress}}/api/mediatr

###

@id=1
POST {{MataAtlantica.API_HostAddress}}/api/categorias/{{id}}
Content-Type: application/json
{
  "Nome": "Teste"
}
###

GET {{MataAtlantica.API_HostAddress}}/api/categorias
Authorization: Bearer CfDJ8JmAdGC8KYRLgwDEJfIKcw_khxHELlKkABXnr6Vu88VQ-MQGXNomnpYAYmQtp2sKroicO0tMW_M9Zaws0SSbqw0cmLmnhcJkg4ax-YnPHJkxtoH8-kqUywkPKbS8n1-TCGCuxVrNG-0UvExu6t04V-iJiGYFt9n1W0Ibr-waBy5zu6Q7VKhJQaGuCAksLStruyvGOwNUGWfSaTnaLAYTs55ftANiyx1F5v6Qvr3MiX5M6l3GzTNsrQ6eVaxZGjtEKivyrNEiBmr5TaKsNP5nmD7yj6ewKSgpOBnYADgDW1I7IY_nfyW9KpIO9bYe_xJznfkFgX8c3dvb-mDE1NSfsl7IqMNqXsLl4WC4fbxMa2hQ3YSEKOCn85qJZsaVKXhsp3vNf63yVu-lJQQIS-Pv0ePsjyJd1P-6A2Usj2DgFUEyAw7Q42gL23xLCZusa626Wzi47qHeaCOf_4KV2KxrxFSm3fGeuq4zyOcL3zFSaJJGWsi6XOQUBD253v9jR0RZnMHNOdh21PCkwIoFVHV1ip34CwzZvx3Ol9V7RERBSzQcp7JM2v2hFpfQcDzoSszc4JJAmYTR6jmccxtTSUnXbEd-xAhbqOeISNrdvXEBU3aijOFfqeAdpA8ukjxomjRdoxUJVSToCAyqkgT1sCqO5RUMvtDUyiRBYsqseQIn4RTWvTMc7h_G2K1ngaFF-SepteU9yN3KLtJj5tKBf0Sf-_hOuV7uOv77vQmR6tAm_vZO

###

POST {{MataAtlantica.API_HostAddress}}/api/usuarios
Content-Type: application/json

{
  "Nome": "Alexandre",
  "Sobrenome": "Maciel",
  "Login": "alexandre.maciele4@gmail.com",
  "Senha": "Ph1l0s0phers@1",
  "Endereco": {
    "Rua": "Rua nova",
    "Bairro": "Bairro bem legal",
    "CEP": "123123",
    "Numero": "1231",
    "Cidade": "cIDADE NOVA",
    "UF": "SE"
  }
}

###

POST {{MataAtlantica.API_HostAddress}}/api/usuarios/login
Content-Type: application/json

{
  "Login": "alexandre.maciele@gmail.com",
  "Senha": "Ph1l0s0phers@1"
}


###

GET {{MataAtlantica.API_HostAddress}}/api/teste
Authorization: Bearer CfDJ8JmAdGC8KYRLgwDEJfIKcw-KxeO1MSO27wlSzadb6VKaoj3f4lx41pIopTWc9C56bYDegv9Z-f20EEI9-V8L8WO2CweyiM4OORo-UB9aiXIvdO2D8oVEUosu5ay8KzqutLi5lWly_SkN7Ldvh-ZdKHDjkJVQWkX42Uloc-RMA9VUGq49oe7-xDIfAEtubPiaZdVr4M5qvd-d8NjvYTG0BsV_n29kCrTjV83zcwX3NzSmX4Ju-FG2MWYKHU2jEbLl89oHREsiMk35Io2SZ88_2I99KdvEhjH3H0AlDHRYcKh8ksQInnz1Hzabl_1OLu5VwOxWsdHsYhnyYMyuC37o3h1yKZWngDeGYQe411B9e8vhXSWM7in0SbfsbC1gJ7bFLuUglibKitqj3jem4OhsIjt9C7EgL4VvLW3IqngSiI2NEvFlHnDk1DGm_VVGxBDWDwu_VHqSu9OkMxgJX_7gylXx2zmZ8cVX0eleU_Rl8Qj8r0mVXZBOMjt4T4X9IV1spT5TzcIRD2kSR6YqUkHL72pkSCLwz4OQaEqn2p01235yOB2pX-Mj2AgnpyCrLeq94Cn2p9ByqGHLWlWmUf6VTJwfEb5OtGwpdetaVMOk55elOQbqxu6qcBMOl4RS_C-j021p_28fa8oL6OMFJORl5Vksg8rmWkBM3HjXj4j2xynHo-cD_wYOn0VdL9fljs6eBO5pVS2xGD65RGysapCN4FHNFehhhxZwaNB6dtQnSObG
Cache-Control: no-cache