apiVersion: apps/v1
kind: Deployment
metadata:
  name: mata-atlantica-db-deployment
  labels:
    app: mata-atlantica-db
spec:
  selector:
    matchLabels:
      app: mata-atlantica-db
  template:
    metadata:
      labels:
        app: mata-atlantica-db
    spec:
      containers:
      - name: mata-atlantica-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: "Password@123456"
        ports:
        - containerPort: 1433

---

# Cria um loadbalancer na frente do servico para que ele possa 
# ser acessado externamente
apiVersion: v1
kind: Service
metadata:
  name: mata-atlantica-port-db
spec:
  type: LoadBalancer
  selector:
    app: mata-atlantica-db
  ports:
  - port: 1433
    targetPort: 1433


---

# Serve para expor o servico atraves de um "nome"
apiVersion: v1
kind: Service
metadata:
  name: mata-atlantica-local-connection-db
spec:
  selector:
    app: mata-atlantica-db
  ports:
  - port: 1433


