apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-deployment
  labels:
    app: curl
spec:
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: alpine/curl
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: curl-lb
spec:
  type: LoadBalancer
  selector:
    app: curl
  ports:
  - port: 80
    targetPort: 80